---
apiVersion: v1
data:
  mandelbrot.conf: |
    ServerName ${SERVER_NAME}
    ErrorLog /dev/stdout
    TransferLog /dev/stdout
    <VirtualHost *:8080>
      ServerName https://${SERVER_NAME}
      ServerAdmin webmaster@localhost
      DocumentRoot /var/www/html
      Header set Access-Control-Allow-Origin "${SERVER_NAME}"
      ErrorLog /dev/stdout
      TransferLog /dev/stdout
      KeepAlive Off
      ExpiresActive On
      ExpiresDefault "access plus 1 hour"
      Header append Cache-Control "public"
    </VirtualHost>
    <IfModule mpm_prefork_module>
      ServerLimit 32
      StartServers 32
      MaxClients 32
      MaxRequestWorkers 32
    </IfModule>
kind: ConfigMap
metadata:
  name: apache-config
