namePrefix: mandelbrot-bardin-haus

commonLabels:
  app-common: helloCommon

commonAnnotations:
  annotation-common: helloCommon

resources:
- deployment.yaml
- configmap.yaml
- ingress.yaml
- hpa.yaml

configMapGenerator:
- name: template-vars
  literals:
  - SERVER_NAME=

vars:
- name: SERVER_NAME
  objref:
    kind: ConfigMap
    name: template-vars
    apiVersion: v1
  fieldref:
    fieldpath: data.SERVER_NAME
