---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: mandelbrot-

commonLabels:
  app: mandelbrot

commonAnnotations:
  common: hello

resources:
- deployment.yaml
- configmap.yaml
- ingress.yaml
- hpa.yaml
- service.yaml

configMapGenerator:
- name: overlay-vars
  literals:
  - SERVER_NAME=

vars:
- name: SERVER_NAME
  objref:
    kind: ConfigMap
    name: overlay-vars
    apiVersion: v1
  fieldref:
    fieldpath: data.SERVER_NAME
